services:
  pagelite-server:
    image: sstarbucks/pagelite-server:latest
    container_name: pagelite-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - USER=admin
      - PASS=admin
      - MAX_UPLOAD_MB=50
    volumes:
      - ./data:/app/data
 